storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: Komodo
    group: core
    url: "https://komodo.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: Fenrir
    group: hardware
    url: "https://fenrir.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Draugr
    group: hardware
    url: "https://draugr.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: TrueNAS
    group: core
    url: "https://true-nas.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Termix
    group: core
    url: "https://termix.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Immich
    group: service
    url: "https://immich.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Stirling-PDF
    group: service
    url: "https://pdf.kluhan.dev/"
    interval: 1m
    conditions:
      - "[STATUS] == 401 || [STATUS] == 200"

      
